---
contentdir: content
layoutdir: layouts
publishdir: public
builddrafts: false
canonifyurls: true
disablerss: true
paginate: 3
MetaDataFormat: yaml
baseURL: http://stefansuciu.ro/
date: "2020-05-01"
taxonomies:
  tag: tags
  category: categories
  series: series
permalinks:
  posts: '/:year/:month/:title/'
params:
  Title: "Ștefan Suciu's Blog"
  DateForm: "2006-01-02"
  Author: "Ștefan Suciu"
  TwitterUser: stefbv70
  DisqusUser: stefansuciu
  Github:
    Head: master
    URL: http://github.com/stefansbv/stefansuciu.ro.git
  GoogleAnalytics: UA-62428437-1
  LanyonOptions: sidebar-overlay theme-base-08
